language: java
sudo: false

jdk:
- oraclejdk8

before_install:
- wget https://archive.apache.org/dist/maven/maven-3/3.5.3/binaries/apache-maven-3.5.3-bin.zip
- unzip -qq apache-maven-3.5.3-bin.zip
- export M2_HOME=$PWD/apache-maven-3.5.3
- export PATH=$M2_HOME/bin:$PATH
- echo "MAVEN_OPTS='-Xmx1g -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss:SSS'" > ~/.mavenrc

install:
- mvn -f releng/maven-plugins/pom.xml install
- mvn -f recipes/pom.xml install

script:
- mvn -f releng/p2/pom.xml package

