language: java
sudo: false

jdk:
- openjdk8
- openjdk10
- openjdk11

matrix:
  allow_failures:
  - jdk: openjdk11

before_install:
- wget https://archive.apache.org/dist/maven/maven-3/3.6.0/binaries/apache-maven-3.6.0-bin.zip
- unzip -qq apache-maven-3.6.0-bin.zip
- export M2_HOME=$PWD/apache-maven-3.6.0
- export PATH=$M2_HOME/bin:$PATH
- export MAVEN_OPTS='-Xmx1g -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss:SSS -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn'
- which mvn
- mvn --version

install:
- mvn -e -f releng/maven-plugins/pom.xml install

script:
- travis_wait 30 mvn -f recipes/pom.xml install  > build.log 2>&1
- travis_wait 20 mvn -f releng/p2/pom.xml package >> build.log 2>&1

after_failure:
- tail --lines=300 build.log


